# Generated by Django 5.0.2 on 2024-09-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('bn_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alpha_code', models.CharField(blank=True, max_length=5, null=True)),
                ('numeric_code', models.IntegerField(blank=True, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=30, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('division_name_bangla', models.CharField(blank=True, max_length=120, null=True)),
                ('division_code', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['division_name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=120)),
                ('district_name_bangla', models.CharField(blank=True, max_length=120, null=True)),
                ('district_code', models.PositiveIntegerField(blank=True, null=True)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.division')),
            ],
            options={
                'ordering': ['district_name'],
            },
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thana_name', models.CharField(max_length=120)),
                ('thana_name_bn', models.CharField(blank=True, max_length=120, null=True)),
                ('thana_code', models.PositiveIntegerField(blank=True, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.district')),
            ],
            options={
                'ordering': ['thana_name'],
            },
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_office_name', models.CharField(max_length=120)),
                ('post_office_name_bangla', models.CharField(blank=True, max_length=120, null=True)),
                ('post_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('thana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.thana')),
            ],
            options={
                'ordering': ['post_code'],
            },
        ),
    ]
