# Generated by Django 5.0.2 on 2024-03-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
