# Generated by Django 5.0.2 on 2024-09-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_candidateapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Permanent'), ('Part Time', 'Temporary'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Contract', 'Contract')], default='Full Time', max_length=50),
        ),
    ]
