# Generated by Django 5.0.2 on 2024-09-28 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A(+ve)'), ('A-', 'A(-ve)'), ('B+', 'B(+ve)'), ('B-', 'B(-ve)'), ('O+', 'O(+ve)'), ('O-', 'O(-ve)'), ('AB+', 'AB(+ve)'), ('AB-', 'AB(-ve)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact',
            field=models.CharField(help_text='Format (ex: 0123456789)', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0123456789)')], verbose_name='Mobile Phone #'),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='weight(kg)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married ', 'Married '), ('Single ', 'Single ')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nid',
            field=models.CharField(help_text='Numeric 10/13/17 digits (ex: 1234567890)', max_length=17, null=True, validators=[django.core.validators.RegexValidator('^(\\d{10}|\\d{13}|\\d{17})$', message='Numeric 10/13/17 digits (ex: 1234567890)')], verbose_name='National ID Number (NID)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.CharField(help_text='Alphanumeric 9 characters (ex: PA3456789)', max_length=9, null=True, validators=[django.core.validators.RegexValidator('^([A-Z]{2}\\d{7}|[A-Z]{1}\\d{8})$', message='Alphanumeric 9 characters (ex: PA3456789)')], verbose_name='Passport Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Jainism', 'Jainism'), ('Judaism', 'Judaism'), ('Sikhism', 'Sikhism'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='Format (ex: 0123456789)', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0123456789)')], verbose_name='Mobile Phone #'),
        ),
    ]
