# Generated by Django 5.0.2 on 2024-09-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('present_salary', models.CharField(help_text='TK/Month', max_length=30)),
                ('expected_salary', models.CharField(help_text='TK/Month', max_length=30)),
                ('job_level', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Top Level', 'Top Level')], max_length=50)),
                ('job_type', models.CharField(choices=[('Full Time', 'Permanent'), ('Part Time', 'Temporary'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Contract', 'Contract')], default='Full Time', max_length=50)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae')),
            ],
        ),
    ]
