# Generated by Django 5.0.2 on 2024-09-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('resume', '0005_releventinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('functional_skill', models.BooleanField(default=False)),
                ('special_skill', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='academic',
            name='award',
        ),
        migrations.RemoveField(
            model_name='academic',
            name='institution',
        ),
        migrations.AddField(
            model_name='academic',
            name='achievement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academic',
            name='duration',
            field=models.CharField(help_text='Duration(Years) i.e 2024', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='academic',
            name='institute_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Institute Name'),
        ),
        migrations.AddField(
            model_name='academic',
            name='is_visible',
            field=models.BooleanField(default=True, help_text="Show this degree in summary view at employer's end"),
        ),
        migrations.AddField(
            model_name='academic',
            name='major',
            field=models.CharField(help_text='Concentration/Major/Group', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='year',
            field=models.CharField(help_text='Expected Year of Passing', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academic',
            name='education_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.educationdegree'),
        ),
        migrations.AddField(
            model_name='academic',
            name='education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.educationlevel'),
        ),
        migrations.AddField(
            model_name='academic',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.educationresult'),
        ),
        migrations.CreateModel(
            name='ProfessionalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=255)),
                ('duration_start', models.DateField()),
                ('duration_end', models.DateField()),
                ('location', models.TextField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=255)),
                ('topic_covered', models.CharField(max_length=255)),
                ('training_year', models.CharField(max_length=4)),
                ('institute', models.CharField(max_length=255)),
                ('duration', models.CharField(help_text='85 Hours', max_length=255)),
                ('location', models.TextField()),
                ('certificate_link', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.country')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae')),
            ],
        ),
    ]
