# Generated by Django 5.0.2 on 2024-09-29 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_employment_expertisearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='how_learn',
            field=models.CharField(choices=[('Self', 'Self'), ('Job', 'Job'), ('Education', 'Education'), ('Professional Training', 'Professional Training')], help_text='How did you learn the skill?', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('reading', models.CharField(choices=[('High', 'Hight'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('writing', models.CharField(choices=[('High', 'Hight'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('speaking', models.CharField(choices=[('High', 'Hight'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae')),
            ],
        ),
    ]
