# Generated by Django 5.0.2 on 2024-09-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_skill_how_learn_languageproficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_on', models.DateField()),
                ('url', models.URLField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LinkAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_account', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('GitHub', 'GitHub'), ('YouTube', 'YouTube'), ('Dribbble', 'Dribbble'), ('Codeforces', 'Codeforces'), ('Hackerrank', 'Hackerrank'), ('Leetcode', 'Leetcode'), ('Others', 'Dribbble')], max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_on', models.DateField()),
                ('url', models.URLField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_on', models.DateField()),
                ('url', models.URLField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_on', models.DateField()),
                ('url', models.URLField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='referee',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='position',
        ),
        migrations.AddField(
            model_name='referee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='organization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='phone_office',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='phone_personal',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='relation',
            field=models.CharField(choices=[('Relative', 'Relative'), ('Family Friend', 'Family Friend'), ('Academic', 'Academic'), ('Professional', 'Professional'), ('Others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Experince',
        ),
    ]
