# Generated by Django 5.0.2 on 2024-09-30 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_award_linkaccount_other_portfolio_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae'),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae'),
        ),
        migrations.AddField(
            model_name='linkaccount',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae'),
        ),
        migrations.AddField(
            model_name='other',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae'),
        ),
        migrations.AddField(
            model_name='project',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae'),
        ),
        migrations.AddField(
            model_name='publication',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae'),
        ),
    ]
