# Generated by Django 5.0.2 on 2024-09-30 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('resume', '0010_award_cv_expertisearea_cv_linkaccount_cv_other_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type', models.CharField(choices=[('Information Technology', 'It'), ('Finance', 'Finance'), ('Health Care', 'Healthcare'), ('Education', 'Education'), ('Manufacturing', 'Manufacturing'), ('Government', 'Government'), ('Retail', 'Retail'), ('Business', 'Business'), ('Other', 'Other')], default='Business', max_length=50)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.curriculumvitae')),
                ('functional_skill', models.ManyToManyField(blank=True, related_name='functional_prefered_areas', to='resume.skillconfig')),
                ('preferred_job_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerered_areas', to='address.district')),
                ('special_skill', models.ManyToManyField(related_name='special_prefered_areas', to='resume.skillconfig')),
            ],
        ),
    ]
